name: CI

on:
  push:
    tags:
      - 'v*.*.*'
    branches: ["main", "feature/**"]
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - 'cmd/**'
      - 'pkg/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
      - name: Set version
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            APP_VERSION=${VERSION}
            DOCKER_TAG=${VERSION}
          else
            SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)
            VERSION="0.1.0+${GITHUB_SHA}"
            APP_VERSION=${GITHUB_SHA}
            DOCKER_TAG="0.1.0-${SHORT_SHA}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "docker_tag=$DOCKER_TAG" >> $GITHUB_OUTPUT
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.K8S_CONTROLLER_TOKEN }}
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ steps.vars.outputs.owner_lc }}/app:${{ steps.vars.outputs.app_version }} .
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          scan-ref: ghcr.io/${{ steps.vars.outputs.owner_lc }}/app:${{ steps.vars.outputs.app_version }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1
      - name: Publish Docker image
        run: docker push ghcr.io/${{ steps.vars.outputs.owner_lc }}/app:${{ steps.vars.outputs.app_version }}